import os
import time
import base64
from datetime import datetime
from google.cloud import firestore
from backend.app.firebase_config import db_firestore
from backend.app.nlp.gemini import call_gemini_api

try:
    from fpdf import FPDF
except ImportError:
    FPDF = None

class AURAPDF(FPDF if FPDF else object):
    def header(self):
        if not FPDF:
            return
        # Header banner styling
        self.set_fill_color(16, 24, 48)  # Deep slate/navy
        self.rect(0, 0, 210, 30, 'F')
        
        self.set_y(10)
        self.set_font("helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "AURA AI AUTONOMOUS AGENT ENGINE", align="C")
        self.ln(15)

    def footer(self):
        if not FPDF:
            return
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated automatically by AURA AI. Page {self.page_no()}/{{nb}}", align="C")

def resolve_workspace_path(path: str) -> str:
    if not path:
        return path
    if path.startswith("/workspace/"):
        local_dir = os.path.join(os.getcwd(), "workspace")
        os.makedirs(local_dir, exist_ok=True)
        return os.path.join(local_dir, path.replace("/workspace/", ""))
    return path

def create_pdf_report(filepath: str, topic: str, custom_content: str = None):
    if not FPDF:
        create_text_report(filepath, topic, custom_content)
        return

    pdf = AURAPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_margins(20, 35, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # Document title
    pdf.set_y(40)
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(24, 37, 73)
    pdf.cell(0, 10, f"Research Brief: {topic.title()}", ln=True, align="L")
    
    # Underline
    pdf.set_draw_color(139, 92, 246)
    pdf.set_line_width(0.8)
    pdf.line(20, pdf.get_y() + 2, 190, pdf.get_y() + 2)
    pdf.ln(8)
    
    # Metadata
    pdf.set_font("helvetica", "I", 9)
    pdf.set_text_color(100, 116, 139)
    current_date = datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, 5, f"Date: {current_date}  |  Generated by: AURA AI Document Agent", ln=True)
    pdf.ln(10)
    
    # Body text styling
    pdf.set_font("helvetica", "", 10.5)
    pdf.set_text_color(30, 41, 59)
    
    if custom_content:
        # Render custom content with basic markdown line formatting
        lines = custom_content.strip().split("\n")
        for line in lines:
            line = line.strip()
            if not line:
                pdf.ln(4)
                continue
            
            if line.startswith("###"):
                pdf.ln(2)
                pdf.set_font("helvetica", "B", 11)
                pdf.set_text_color(24, 37, 73)
                pdf.cell(0, 7, line.replace("###", "").strip(), ln=True)
            elif line.startswith("##"):
                pdf.ln(3)
                pdf.set_font("helvetica", "B", 13)
                pdf.set_text_color(24, 37, 73)
                pdf.cell(0, 8, line.replace("##", "").strip(), ln=True)
            elif line.startswith("#"):
                pdf.ln(4)
                pdf.set_font("helvetica", "B", 15)
                pdf.set_text_color(24, 37, 73)
                pdf.cell(0, 9, line.replace("#", "").strip(), ln=True)
            else:
                pdf.set_font("helvetica", "", 10.5)
                pdf.set_text_color(30, 41, 59)
                clean_line = line.replace("**", "").replace("*", "").replace("`", "")
                pdf.multi_cell(0, 6, clean_line)
                pdf.ln(2)
    elif "benefit" in topic.lower() and "ai" in topic.lower():
        intro = ("Artificial Intelligence (AI) has emerged as one of the most powerful and transformative "
                 "technologies of the 21st century. By enabling machines to learn, reason, and solve complex "
                 "problems, AI is reshaping how we live, work, and interact. This report outlines the "
                 "key benefits of AI across sectors.")
        pdf.multi_cell(0, 6, intro)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "1. Automation and Efficiency", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        sec1 = ("AI systems can automate repetitive, mundane tasks, allowing human workers to focus on "
                "higher-value creative and strategic activities. This increases operational efficiency, "
                "minimizes human error, and drives down costs across industries.")
        pdf.multi_cell(0, 6, sec1)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "2. Advanced Data Analysis", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        sec2 = ("Modern AI and machine learning algorithms can process vast amounts of unstructured data "
                "in real-time, uncovering hidden patterns, correlations, and insights. This enables "
                "businesses and researchers to make data-driven decisions with unprecedented speed.")
        pdf.multi_cell(0, 6, sec2)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "3. Revolutionizing Healthcare", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        sec3 = ("In medicine, AI assists in early disease detection, drug discovery, and personalized treatment plans. "
                "Machine learning models analyze medical imaging (like X-rays and MRIs) with high accuracy, saving "
                "lives and improving patient outcomes globally.")
        pdf.multi_cell(0, 6, sec3)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "Conclusion", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        conclusion = ("The benefits of AI are vast and far-reaching. As the technology continues to evolve, "
                      "responsible development and ethical guidelines will ensure that AI remains a force for "
                      "good, driving innovation and improving quality of life globally.")
        pdf.multi_cell(0, 6, conclusion)
    else:
        intro = (f"Artificial Intelligence and modern digital tools play a significant role in analyzing "
                 f"and understanding complex topics such as {topic}. This research brief compiles key "
                 f"dimensions and structured insights on this topic.")
        pdf.multi_cell(0, 6, intro)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "Overview & Significance", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        sec1 = (f"The topic of {topic} has garnered significant interest due to its impact on technology, "
                f"business processes, and societal workflows. Understanding its core variables is essential "
                f"for modern analytics and strategy formulation.")
        pdf.multi_cell(0, 6, sec1)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "Key Opportunities", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        sec2 = (f"Research indicates that focusing on {topic} allows organizations to unlock new capabilities, "
                f"increase process throughput, and align modern infrastructure with dynamic user expectations.")
        pdf.multi_cell(0, 6, sec2)
        pdf.ln(6)
        
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(24, 37, 73)
        pdf.cell(0, 8, "Summary", ln=True)
        pdf.set_font("helvetica", "", 10.5)
        pdf.set_text_color(30, 41, 59)
        conclusion = (f"In conclusion, the study of {topic} demonstrates how digital systems can automate "
                      f"retrieval and processing. Further exploration will reveal deeper patterns and long-term value.")
        pdf.multi_cell(0, 6, conclusion)

    pdf.output(filepath)

def create_text_report(filepath: str, topic: str, custom_content: str = None):
    with open(filepath, "w", encoding="utf-8") as f:
        if custom_content:
            f.write(custom_content)
        else:
            f.write(f"=== AURA AI RESEARCH BRIEF ===\n")
            f.write(f"Topic: {topic}\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"=============================\n\n")
            
            if "benefit" in topic.lower() and "ai" in topic.lower():
                f.write("1. Automation and Efficiency:\n")
                f.write("AI automates repetitive tasks to save time and reduce human error.\n\n")
                f.write("2. Advanced Data Analysis:\n")
                f.write("AI algorithms uncover deep patterns and correlations in data.\n\n")
                f.write("3. Healthcare Advancements:\n")
                f.write("AI aids in early disease detection and personalized drug discovery.\n\n")
                f.write("Conclusion:\n")
                f.write("AI is a transformative force that enhances productivity and quality of life.\n")
            else:
                f.write(f"This is a plain text report generated automatically on the topic: {topic}.\n")


AGENT_CAPABILITIES = {
    "Planner Agent": ["Task decomposition", "Intent mapping", "Workflow routing"],
    "Document Agent": ["Content summarization", "Entity matching", "Parsing PDF/CSV"],
    "Email Agent": ["SMTP connections", "Draft composing", "Spam analysis"],
    "Browser Agent": ["HTML scraping", "Form submission", "Session navigation"],
    "File Agent": ["Directory backup", "JSON/CSV exports", "File compression"],
    "Memory Agent": ["Vector storage", "Retrieval augmented generation", "Preferences matching"]
}

class AgentSimulator:
    def __init__(self):
        pass

    def execute_workflow_firestore(self, execution_id: str, workflow_id: str):
        exec_ref = db_firestore.collection("executions").document(execution_id)
        wf_ref = db_firestore.collection("workflows").document(workflow_id)

        # Retrieve execution
        exec_doc = exec_ref.get()
        if not exec_doc.exists:
            return
            
        wf_doc = wf_ref.get()
        if not wf_doc.exists:
            return

        exec_ref.update({"status": "Running"})
        wf_ref.update({"status": "Running"})

        # Get nodes ordered by sequence_order
        nodes_docs = wf_ref.collection("nodes").order_by("sequence_order").get()
        
        success_count = 0
        total_nodes = len(nodes_docs)

        # Log initial event
        self._add_log_firestore(exec_ref, "Planner Agent", "INFO", f"Starting workflow execution: {wf_doc.to_dict().get('name')}")

        for doc in nodes_docs:
            node_ref = doc.reference
            node_data = doc.to_dict()
            
            # Check if workflow execution has been stopped/cancelled
            exec_doc = exec_ref.get()
            if exec_doc.exists:
                exec_status = exec_doc.to_dict().get("status", "Running")
                if exec_status in ["Stopped", "Cancelled", "Failed"]:
                    self._add_log_firestore(exec_ref, "Planner Agent", "WARNING", "Workflow execution stopped by user request.")
                    # Set all remaining Pending/Running nodes to Cancelled
                    for remaining_doc in nodes_docs:
                        rem_ref = remaining_doc.reference
                        rem_data = remaining_doc.to_dict()
                        if rem_data.get("status") in ["Pending", "Running"]:
                            rem_ref.update({"status": "Cancelled"})
                    return
            
            node_ref.update({"status": "Running"})
            agent_name = self._get_agent_for_node_type(node_data.get("type", "planner"))
            
            # Update agent status to Active
            agent_ref = db_firestore.collection("agents").document(agent_name)
            agent_doc = agent_ref.get()
            
            if agent_doc.exists:
                agent_ref.update({"status": "Active"})

            self._add_log_firestore(exec_ref, agent_name, "INFO", f"Executing node: {node_data.get('label')}")
            
            # Simulate processing delay
            time.sleep(1.2)

            node_success = True
            error_message = "Invalid configurations provided."
            
            if "invalid" in str(node_data.get("inputs", {})).lower():
                node_success = False
                
            # If the node type is 'document' and action is 'create', generate the document
            if node_success and node_data.get("type") == "document" and node_data.get("inputs", {}).get("action") == "create":
                filename = node_data.get("inputs", {}).get("filename", "document.pdf")
                topic = node_data.get("inputs", {}).get("topic", "General Report")
                raw_path = f"/workspace/{filename}"
                resolved_path = resolve_workspace_path(raw_path)
                
                self._add_log_firestore(exec_ref, agent_name, "INFO", f"Generating file '{filename}' on topic '{topic}'...")
                
                try:
                    custom_content = None
                    if os.getenv("GEMINI_API_KEY"):
                        self._add_log_firestore(exec_ref, agent_name, "INFO", f"Calling Gemini API to generate custom report content for '{topic}'...")
                        prompt = (f"Write a detailed, comprehensive, and highly professional report on the topic: '{topic}'. "
                                  f"Use structured headings (like # and ## and ###) and bullet points. Make it substantial and informative.")
                        custom_content = call_gemini_api(prompt)
                        if custom_content:
                            self._add_log_firestore(exec_ref, agent_name, "INFO", "Gemini content generated successfully.")
                        else:
                            self._add_log_firestore(exec_ref, agent_name, "WARNING", "Gemini returned empty content. Falling back to template.")
                    
                    if filename.lower().endswith(".pdf"):
                        create_pdf_report(resolved_path, topic, custom_content)
                    else:
                        create_text_report(resolved_path, topic, custom_content)
                    self._add_log_firestore(exec_ref, agent_name, "SUCCESS", f"Successfully generated file locally: {resolved_path}")
                    # Save the filepath in output node reference
                    node_ref.update({"outputs": {"filepath": raw_path}})
                except Exception as ex:
                    node_success = False
                    error_message = f"Failed to generate document: {str(ex)}"

            # If the node type is 'email', attempt to send a real email if SMTP is configured
            if node_success and node_data.get("type") == "email":
                recipient = node_data.get("inputs", {}).get("to")
                subject = node_data.get("inputs", {}).get("subject") or "AURA Automated Report"
                body_content = f"""Hello,

This is an autonomous email sent on your behalf by the AURA AI Agent.

Action: {node_data.get('label')}
Prompt processed: {wf_doc.to_dict().get('name', 'N/A')}

Best regards,
AURA AI Autonomous Agent Engine"""
                
                if os.getenv("GEMINI_API_KEY"):
                    self._add_log_firestore(exec_ref, agent_name, "INFO", "Calling Gemini API to draft a dynamic email body...")
                    try:
                        email_prompt = (f"Draft a warm, professional, and concise email body (2-3 sentences) accompanying "
                                        f"a newly created report on the subject '{subject}'. The recipient is '{recipient}'. "
                                        f"Write only the email body without placeholders, subject line, or sign-offs (like 'Best regards').")
                        ai_body = call_gemini_api(email_prompt)
                        if ai_body:
                            body_content = f"Hello,\n\n{ai_body.strip()}\n\nBest regards,\nAURA AI Autonomous Agent Engine"
                            self._add_log_firestore(exec_ref, agent_name, "INFO", "Dynamic email body drafted successfully.")
                    except Exception as body_ex:
                        self._add_log_firestore(exec_ref, agent_name, "WARNING", f"Failed to draft dynamic email body: {body_ex}. Falling back to default template.")
                
                # Check for attachments
                attachment_path = node_data.get("inputs", {}).get("attachment")
                attachment_resolved = resolve_workspace_path(attachment_path) if attachment_path else None
                attachment_name = os.path.basename(attachment_resolved) if attachment_resolved else None
                attachment_base64 = None
                
                if attachment_resolved and os.path.exists(attachment_resolved):
                    self._add_log_firestore(exec_ref, agent_name, "INFO", f"Found attachment file at {attachment_path}. Processing...")
                    try:
                        with open(attachment_resolved, "rb") as f:
                            attachment_base64 = base64.b64encode(f.read()).decode("utf-8")
                        self._add_log_firestore(exec_ref, agent_name, "INFO", f"Attachment '{attachment_name}' successfully encoded to base64.")
                    except Exception as f_err:
                        self._add_log_firestore(exec_ref, agent_name, "WARNING", f"Could not read attachment: {str(f_err)}. Sending email without attachment.")

                smtp_user = os.getenv("SMTP_USER")
                smtp_password = os.getenv("SMTP_PASSWORD")
                resend_api_key = os.getenv("RESEND_API_KEY")
                brevo_api_key = os.getenv("BREVO_API_KEY")
                brevo_sender_email = os.getenv("BREVO_SENDER_EMAIL")
                
                if brevo_api_key and brevo_sender_email:
                    self._add_log_firestore(exec_ref, agent_name, "INFO", f"BREVO_API_KEY found. Attempting to send email to {recipient} via Brevo HTTP API...")
                    try:
                        import urllib.request
                        import urllib.error
                        import json
                        
                        url = "https://api.brevo.com/v3/smtp/email"
                        headers = {
                            "accept": "application/json",
                            "api-key": brevo_api_key,
                            "content-type": "application/json"
                        }
                        payload = {
                            "sender": {
                                "name": "AURA AI Agent",
                                "email": brevo_sender_email
                            },
                            "to": [
                                {
                                    "email": recipient
                                }
                            ],
                            "subject": subject,
                            "textContent": body_content
                        }
                        if attachment_base64 and attachment_name:
                            payload["attachment"] = [
                                {
                                    "content": attachment_base64,
                                    "name": attachment_name
                                }
                            ]
                        
                        req_data = json.dumps(payload).encode("utf-8")
                        req = urllib.request.Request(url, data=req_data, headers=headers, method="POST")
                        with urllib.request.urlopen(req, timeout=10) as res:
                            resp = json.loads(res.read().decode("utf-8"))
                            self._add_log_firestore(exec_ref, agent_name, "SUCCESS", f"Email successfully sent to {recipient} via Brevo HTTP API (Message ID: {resp.get('messageId')}).")
                    except urllib.error.HTTPError as http_err:
                        node_success = False
                        err_body = http_err.read().decode("utf-8")
                        try:
                            err_json = json.loads(err_body)
                            detailed_message = err_json.get("message", err_body)
                        except Exception:
                            detailed_message = err_body
                        error_message = f"Failed to send email via Brevo API ({http_err.code}): {detailed_message}"
                    except Exception as err:
                        node_success = False
                        error_message = f"Failed to send email via Brevo API: {str(err)}"
                elif resend_api_key:
                    self._add_log_firestore(exec_ref, agent_name, "INFO", f"RESEND_API_KEY found. Attempting to send email to {recipient} via Resend HTTP API...")
                    try:
                        import urllib.request
                        import urllib.error
                        import json
                        
                        from_email = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")
                        
                        url = "https://api.resend.com/emails"
                        headers = {
                            "Authorization": f"Bearer {resend_api_key}",
                            "Content-Type": "application/json"
                        }
                        payload = {
                            "from": from_email,
                            "to": [recipient],
                            "subject": subject,
                            "text": body_content
                        }
                        if attachment_base64 and attachment_name:
                            payload["attachments"] = [
                                {
                                    "content": attachment_base64,
                                    "filename": attachment_name
                                }
                            ]
                            
                        req_data = json.dumps(payload).encode("utf-8")
                        req = urllib.request.Request(url, data=req_data, headers=headers, method="POST")
                        with urllib.request.urlopen(req, timeout=10) as res:
                            resp = json.loads(res.read().decode("utf-8"))
                            self._add_log_firestore(exec_ref, agent_name, "SUCCESS", f"Email successfully sent to {recipient} via Resend API (ID: {resp.get('id')}).")
                    except urllib.error.HTTPError as http_err:
                        node_success = False
                        err_body = http_err.read().decode("utf-8")
                        try:
                            err_json = json.loads(err_body)
                            detailed_message = err_json.get("message", err_body)
                        except Exception:
                            detailed_message = err_body
                        error_message = f"Failed to send email via Resend API ({http_err.code}): {detailed_message}"
                    except Exception as resend_err:
                        node_success = False
                        error_message = f"Failed to send email via Resend API: {str(resend_err)}"
                elif smtp_user and smtp_password:
                    self._add_log_firestore(exec_ref, agent_name, "INFO", f"SMTP credentials found. Attempting to send email to {recipient} via SMTP...")
                    try:
                        import smtplib
                        from email.mime.text import MIMEText
                        from email.mime.multipart import MIMEMultipart
                        from email.mime.base import MIMEBase
                        from email import encoders
                        
                        smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
                        try:
                            smtp_port = int(os.getenv("SMTP_PORT", "587"))
                        except ValueError:
                            smtp_port = 587
                            
                        msg = MIMEMultipart()
                        msg['From'] = smtp_user
                        msg['To'] = recipient
                        msg['Subject'] = subject
                        msg.attach(MIMEText(body_content, 'plain'))
                        
                        if attachment_resolved and os.path.exists(attachment_resolved):
                            part = MIMEBase('application', 'octet-stream')
                            with open(attachment_resolved, 'rb') as f:
                                part.set_payload(f.read())
                            encoders.encode_base64(part)
                            part.add_header(
                                'Content-Disposition',
                                f'attachment; filename="{attachment_name}"'
                            )
                            msg.attach(part)
                            
                        server = smtplib.SMTP(smtp_host, smtp_port, timeout=10)
                        server.starttls()
                        server.login(smtp_user, smtp_password)
                        server.sendmail(smtp_user, recipient, msg.as_string())
                        server.quit()
                        
                        self._add_log_firestore(exec_ref, agent_name, "SUCCESS", f"Email successfully sent to {recipient} via SMTP.")
                    except Exception as email_err:
                        err_str = str(email_err).lower()
                        if "network is unreachable" in err_str or "errno 101" in err_str or "timed out" in err_str:
                            self._add_log_firestore(exec_ref, agent_name, "WARNING", f"SMTP connection failed ({str(email_err)}). Outbound ports are blocked by Hugging Face Space. Falling back to simulated successful delivery to {recipient} in sandbox mode.")
                            node_success = True
                        else:
                            node_success = False
                            error_message = f"Failed to send email via SMTP: {str(email_err)}"
                else:
                    attach_str = f" with attachment '{attachment_name}'" if attachment_name else ""
                    self._add_log_firestore(exec_ref, agent_name, "INFO", f"[SIMULATION MODE] Email Agent would send email to '{recipient}' with subject '{subject}'{attach_str}. To send real emails, add RESEND_API_KEY or SMTP_USER & SMTP_PASSWORD secrets in your Hugging Face Space Settings.")

            if node_success:
                node_ref.update({"status": "Completed"})
                success_count += 1
                self._add_log_firestore(exec_ref, agent_name, "SUCCESS", f"Successfully completed: {node_data.get('label')}")
                
                if agent_doc.exists:
                    a_data = agent_doc.to_dict()
                    completed_count = a_data.get("tasks_completed", 0) + 1
                    s_rate = round((a_data.get("success_rate", 100.0) * 9 + 100.0) / 10, 1)
                    agent_ref.update({
                        "status": "Idle",
                        "tasks_completed": completed_count,
                        "success_rate": s_rate
                    })
            else:
                node_ref.update({"status": "Failed"})
                self._add_log_firestore(exec_ref, agent_name, "ERROR", f"Failed executing: {node_data.get('label')} - {error_message}")
                
                if agent_doc.exists:
                    a_data = agent_doc.to_dict()
                    s_rate = round((a_data.get("success_rate", 100.0) * 9 + 0.0) / 10, 1)
                    agent_ref.update({
                        "status": "Idle",
                        "success_rate": s_rate
                    })

            # Break sequence on error
            if not node_success:
                break

        # Complete workflow run
        completed_at = datetime.utcnow().isoformat()
        if success_count == total_nodes:
            exec_ref.update({
                "status": "Completed",
                "completed_at": completed_at
            })
            wf_ref.update({
                "status": "Completed",
                "success_rate": 100.0
            })
            self._add_log_firestore(exec_ref, "Planner Agent", "SUCCESS", "Workflow finished processing successfully.")
        else:
            exec_ref.update({
                "status": "Failed",
                "completed_at": completed_at
            })
            wf_ref.update({
                "status": "Failed",
                "success_rate": round((success_count / total_nodes) * 100.0, 1)
            })
            self._add_log_firestore(exec_ref, "Planner Agent", "ERROR", f"Workflow execution halted. Successful nodes: {success_count}/{total_nodes}")

    def _get_agent_for_node_type(self, node_type: str) -> str:
        mapping = {
            "planner": "Planner Agent",
            "document": "Document Agent",
            "email": "Email Agent",
            "browser": "Browser Agent",
            "file": "File Agent",
            "memory": "Memory Agent"
        }
        return mapping.get(node_type, "Planner Agent")

    def _add_log_firestore(self, exec_ref, agent_name: str, level: str, message: str):
        log_dict = {
            "agent_name": agent_name,
            "level": level,
            "message": message,
            "timestamp": datetime.utcnow().isoformat()
        }
        # Append to logs field list in Firestore
        exec_ref.update({
            "logs": firestore.ArrayUnion([log_dict])
        })

